<?php include "exp/intro.php"; ?>

<body>
    <div class="mainText">


        <span>
            <h1>Lorem ipsum dolor sit amet.</h1>
        </span>

        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam nisi enim unde a inventore, tempore culpa nemo iste et commodi tenetur fugit laborum. Eaque, minus!</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Provident, sint?</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Neque illum quos, error beatae repellat eos sit quibusdam? Obcaecati quae, nobis dolore in modi iure non cumque suscipit quas provident illo corporis temporibus, nihil quis eum pariatur saepe ipsam, molestiae animi labore? Aliquid, at nesciunt dicta laudantium incidunt cum reiciendis ipsa blanditiis autem illum voluptas vero molestiae sapiente suscipit repudiandae iure temporibus id numquam nam odio. Ex deserunt sit odio ipsum nostrum possimus quo! Aliquam sunt voluptas esse et vel voluptatum rerum ad, quisquam nam voluptates quos corporis, totam dolores ullam modi porro facere nesciunt quod. Culpa, fuga nihil! Explicabo quod dolore veniam accusamus dolorum dignissimos facere earum voluptatem enim! Reiciendis architecto earum dolore rerum. Sequi modi recusandae laboriosam iure. Est voluptatem ut impedit temporibus quos odio eligendi repellendus, tempora quasi ex quod quam exercitationem, aliquid cupiditate. Iste mollitia necessitatibus adipisci architecto atque veritatis neque suscipit cum repudiandae fugiat facere veniam, pariatur numquam animi distinctio similique, ipsa dolores beatae rem. Dolore saepe laboriosam odio voluptatem maxime voluptates reprehenderit deserunt aperiam! Nesciunt recusandae harum mollitia saepe earum voluptatum veniam distinctio voluptas! Accusamus nihil, repellat commodi laudantium, aliquam sit voluptates odit labore id eligendi itaque? Sequi ullam, at quam maiores rerum temporibus laudantium?</p>
        <div class="videocontainer">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/SOAGCzqkCCU" title="Player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
        <h2 style=" display: inline;
  border-bottom: 3px solid rgba(238, 111, 87, 0.5);">Lorem, ipsum dolor.</h2>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor vitae qui nam, reprehenderit, consequatur eius nulla laborum blanditiis placeat molestiae quod voluptate temporibus quibusdam iste eum est, ad id? Quibusdam doloribus quasi quis eligendi ex sed voluptas consectetur rem illum iste? Vitae voluptates explicabo libero veniam cum eius nostrum exercitationem dicta aliquam expedita esse reiciendis, ullam, ea cupiditate repellendus doloribus velit excepturi tempore quidem et! Quos recusandae reprehenderit error numquam facere quam, rerum quisquam eveniet sint officiis deleniti dolorum, minus voluptatibus saepe obcaecati harum esse dicta deserunt? Error, voluptate rerum explicabo expedita rem ratione ipsam temporibus eaque nihil amet asperiores iusto minima nemo. Exercitationem aut corrupti, fugiat atque nam officiis culpa assumenda incidunt aliquid accusamus eos aspernatur. Ullam asperiores rem molestiae ut. Deserunt blanditiis doloremque beatae amet cumque nesciunt rem eveniet maxime corporis necessitatibus, error possimus ratione, tempora repellendus laborum a earum eligendi enim, eos placeat totam? Quo, sapiente soluta! Maxime, impedit unde sequi eligendi, veniam asperiores accusamus autem soluta, neque aperiam possimus itaque illo corporis eum? Exercitationem sunt voluptatem illum impedit numquam soluta, recusandae accusantium architecto blanditiis placeat aspernatur natus, molestias tempora veritatis. Recusandae quia mollitia dolor perspiciatis quibusdam est ab sed eius sapiente esse fuga neque cumque in, similique sit? Est voluptatibus corporis magnam animi, id ullam blanditiis? Voluptas obcaecati ab beatae magni tenetur qui eligendi aperiam quisquam iusto, praesentium atque repellendus labore est. Aut veritatis neque veniam, quo esse at pariatur rem eveniet mollitia ratione ad quia nobis molestiae perspiciatis eum. Natus fugit accusamus voluptate error explicabo.</p>
        <h3 style="display: inline;
  border-bottom: 3px solid rgba(238, 111, 87, 0.5);">Lorem ipsum dolor sit amet.</h3>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eveniet tempore perferendis, maiores placeat in obcaecati facere quis dolore impedit qui maxime illum eum expedita officia magnam ipsum deleniti quo nemo, dignissimos soluta. Autem saepe repudiandae quisquam nesciunt asperiores temporibus incidunt, excepturi ipsa quo delectus amet doloremque quaerat quas aliquam non?
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Sunt pariatur repudiandae voluptas neque nemo vitae, aperiam veritatis dicta quasi molestiae magni reprehenderit beatae magnam, earum quis animi velit asperiores est explicabo minima perferendis corrupti nostrum? Ab, dolore cumque! Eius excepturi exercitationem similique tempora maxime animi quo accusantium, dignissimos delectus voluptates minima facere voluptatum iusto voluptatibus esse aperiam nisi ullam repudiandae deserunt sit sed quasi debitis dolorum. Distinctio cumque voluptatum doloremque a tempora quisquam quae impedit placeat debitis possimus, quibusdam sapiente excepturi in, inventore illum! Laudantium tenetur similique recusandae doloremque. Nam ratione sit unde distinctio suscipit placeat magnam dolorum alias commodi?
        </p>
    </div>

</body>
<?php include "exp/end.php"; ?>