<?php include "exp/intro.php"; ?>

<body>
        <div class="csoport">
                <h3>A csapat</h3>
                <img src="info/csoport2.jpg" alt="">
        </div>
        <div class="infoSzoveg">
                <h3>A tagokról:</h3>
                <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nam quaerat earum aperiam voluptatem aliquam amet enim inventore qui molestias ipsam commodi nulla ea explicabo perspiciatis totam sunt sed perferendis repellat quidem, voluptatibus excepturi nostrum! Laboriosam aspernatur accusamus voluptatum officia architecto inventore rerum placeat vitae odio, expedita incidunt? Molestiae ipsam non facilis iste a in, esse quae beatae omnis eligendi. Quis, beatae velit voluptate vel neque aliquam a possimus temporibus repudiandae perferendis quasi sit odio omnis molestiae earum eaque ea ab, autem cumque quisquam dolorum dicta adipisci. Beatae laboriosam laborum vel accusamus facilis sit error nobis, maiores, nesciunt eligendi, quis debitis?</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis nobis harum esse, voluptates inventore laborum a dolorum quam mollitia sequi quisquam aliquam in. Possimus quos voluptatum ea maiores obcaecati impedit libero doloremque fugiat delectus suscipit! Consectetur voluptates eligendi reprehenderit mollitia fugiat quae odit quisquam est. Impedit architecto consequuntur aliquam unde numquam cumque doloremque dolorem voluptas delectus debitis sit, esse laboriosam nulla! Optio repellendus aliquid consequuntur incidunt architecto modi explicabo officiis? Dolorum iure quaerat nostrum et, hic vitae culpa in adipisci voluptates fuga quam ex ab est non autem, molestiae, repellendus explicabo magnam maiores ea animi placeat. Autem necessitatibus in vero.</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsam sequi velit, harum quam consequatur animi natus illum maiores deleniti officiis eius? Temporibus impedit, ullam aspernatur, necessitatibus dolores dolore hic, voluptate assumenda similique voluptatum facere incidunt! Delectus repudiandae accusamus nesciunt! Quia, temporibus repellendus perferendis nesciunt adipisci velit cupiditate non molestiae recusandae dolor quod harum quisquam eos delectus aliquam facere sint rem in consectetur quibusdam dignissimos pariatur tenetur? Atque ducimus consequuntur eveniet modi sint. Eaque ab aliquid, numquam eveniet excepturi repudiandae a.</p>
                <h3>A tájházról:</h3>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Libero cumque alias adipisci minima similique quisquam excepturi? Quam rerum quaerat a deleniti voluptates reprehenderit molestiae error, officia quis rem molestias repudiandae illum ex culpa veniam odio voluptatem autem hic vel iure magni reiciendis, nostrum itaque! Quaerat fuga odit animi soluta qui laudantium voluptate facere, rerum ut, eos officia vitae dignissimos eligendi quisquam quas nobis, deserunt excepturi! Minima, optio quisquam eum facere ad, alias dolores repellendus consequuntur nihil corporis beatae doloribus! Animi quo reiciendis consequatur laudantium excepturi at nam cupiditate nihil atque quisquam, ea quos voluptatum sequi distinctio, dolorem debitis! Corporis ab nesciunt debitis reprehenderit laborum dolorem veritatis? Hic, obcaecati nemo. Labore minus eos error est aspernatur commodi qui cum, voluptate atque eaque autem quam eligendi nobis sapiente voluptatem officiis nisi iure, suscipit porro in dignissimos blanditiis. Quidem rerum facere fuga quo nulla inventore. In sunt accusantium harum deserunt ipsa, rem aliquid!</p>
                <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Totam laboriosam unde modi repellendus porro, iure harum voluptatibus quisquam nobis ducimus, omnis nostrum fugiat quibusdam, exercitationem sit officiis consectetur maxime placeat veritatis. Magnam dolores perferendis fugiat obcaecati, nisi inventore iure assumenda!</p>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error ratione expedita unde dolorum? Accusantium maxime eum recusandae, quae optio nihil aliquam beatae placeat illum quaerat enim expedita nostrum, deserunt qui similique reprehenderit eos error perspiciatis sapiente iste modi? Modi illum repellendus, sed natus pariatur atque accusamus minima nisi vitae eaque laborum quis, beatae, voluptate voluptatem blanditiis ut? Officiis necessitatibus quasi, recusandae tenetur maiores veritatis aut. Adipisci assumenda tempora quaerat? Rem ratione natus vitae quaerat, suscipit, autem doloremque expedita doloribus earum, sed vel similique. Ex quasi laboriosam dolorum, sequi illo blanditiis nobis consequuntur nostrum maiores in facere at inventore id?</p>
        </div>
        <div class="terkep">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2780.884321017666!2d18.09943511556913!3d45.81357507910664!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475d45c4dfe71c2b%3A0xa75b46059925eb0d!2zRXBlcmZhIFTDoWpow6F6!5e0!3m2!1shu!2shu!4v1671185073797!5m2!1shu!2shu" width="700" height="500" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

        </div>
</body>
<?php include "exp/end.php"; ?>